server:
  port: 9093
spring:
  application:
    name: api-sms
  redis:
    port: 6379
    host: 192.168.175.161
  cloud:
    nacos:
      server-addr: 192.168.175.161:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
logging:
  level:
    com.cjx: debug
sms:
  accesskeyId:
  secret:
  signName: 阿里云短信测试
  templateCode: 
  regionId: cn-hangzhou
