server:
  port: 9094
spring:
  application:
    name: api-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.175.161:3306/yingxue?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 20010106
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
      server-addr: 192.168.175.161:8848
  redis:
    host: 192.168.175.161
    port: 6379
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
