server:
  port: 9095
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.175.161:3306/yingxue?serverTimezone=UTC&useSSL=false
    username: root
    password: 20010106
  application:
    name: api-category
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
      server-addr: 192.168.175.161:8848
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl